spring:
  application:
    name: leavecalc

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    time-zone: Asia/Seoul

logging:
  level:
    root: INFO
    com.lawding.leavecalc: INFO

internal:
  secret: ${INTERNAL_AUTH_SECRET}

app:
  db:
    host: ${RDS_HOST}
    port : 3306
    name: ${DB_NAME}
    username: ${DB_USERNAME}
    region: ${AWS_REGION}