spring:
  application:
    name: leavecalc

  datasource:
    url: jdbc:mysql://${RDS_HOST}:3306/${DB_NAME}
    username: ${DB_USERNAME}
    driver-class-name: software.aws.rds.jdbc.mysql.Driver

    hikari:
      maximum-pool-size: 5
      minimum-idle: 0 # 요청 없으면 커넥션 아예 안 들고 있게
      max-lifetime: 600000  # 10분 동안 안 쓰면 닫음 (토큰 만료 15분 보다 짧게)
      idle-timeout: 600000 # 10분마다 강제로 교체
      connection-timeout: 30000 # 30초 안에 커넥션 못 빌리면 실패
      validation-timeout: 5000 # 커넥션 검증 최대 5초
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    time-zone: Asia/Seoul

logging:
  level:
    root: INFO
    com.lawding.leavecalc: INFO

app:
  db:
    host: ${RDS_HOST}
    port: 3306

internal:
  secret: ${INTERNAL_AUTH_SECRET}