spring:
  application:
    name: leavecalc

  datasource:
    url: jdbc:mysql://${RDS_HOST}:3306/${DB_NAME}
    username: ${DB_USERNAME}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    time-zone: Asia/Seoul

logging:
  level:
    root: INFO
    com.lawding.leavecalc: INFO

app:
  db:
    host: ${RDS_HOST}
    port: 3306

internal:
  secret: ${INTERNAL_AUTH_SECRET}