spring:
  datasource:
    url: jdbc:mysql://lawdingdb.cdsmiu2m0dc8.ap-northeast-2.rds.amazonaws.com:3306/leave_calculator?useSSL=false&allowPublicKeyRetrieval=true
    username: ashine   # 로컬 개발용 계정
    password: divergence250224!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
