spring:
  application:
    name: leavecalc

  datasource:
    url: jdbc:mysql://${RDS_HOST}:3306/${DB_NAME}
    username: ${DB_USERNAME}
    driver-class-name: software.aws.rds.jdbc.mysql.Driver

    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      max-lifetime: 840000 # 14분 (토큰 만료 15분 보다 짧게)
      idle-timeout: 600000 # 10분
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    time-zone: Asia/Seoul

logging:
  level:
    root: INFO
    com.lawding.leavecalc: INFO

app:
  db:
    host: ${RDS_HOST}
    port: 3306

internal:
  secret: ${INTERNAL_AUTH_SECRET}